@hostname = http://localhost:3003

GET {{hostname}}/api/blogs

###
POST {{hostname}}/api/blogs
Content-Type: application/json

{
    "title": "testiä",
    "author": "0szdgkjkzdgj",
    "url": "kljglk",
    "likes": 0
}