@hostname = http://localhost:3003

POST {{hostname}}/api/users
Content-Type: application/json

{
    "username": "mhksj",
    "name": "maija mehiläinen",
    "password": "123sfsdfsf",
    "blogs": []
}