@hostname = http://localhost:3003

POST {{hostname}}/api/blogs
Content-Type: application/json

{
    "title": "kolmas uusi blogi",
    "author": "0szdgkjkzdgj",
    "url": "kdkjgldjk",
    "likes": 10
}