@hostname = http://localhost:3003

POST {{hostname}}/api/blogs
Content-Type: application/json

{
    "title": "uusi blogi",
    "author": "oskljg",
    "url": "jotain",
    "likes": 2,
    "userId": "634814c80f5618a4d39f0c86"
}
